//
// Created by Leonard on 2018/09/23.
//

#ifndef OPENGLLEARNING_FREETYPEERRORWRAPPER_HPP
#define OPENGLLEARNING_FREETYPEERRORWRAPPER_HPP

#include <cassert>

#define FREE_TYPE_ERROR_WRAPPER(x) assert(x == 0)

#endif //OPENGLLEARNING_FREETYPEERRORWRAPPER_HPP
